version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 9.0
  pre_build:
    commands:
      - dotnet restore src/LibraryApi.API/LibraryApi.API.csproj
  build:
    commands:
      - dotnet build src/LibraryApi.API/LibraryApi.API.csproj -c Release
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ src/LibraryApi.API/LibraryApi.API.csproj
artifacts:
  files:
    - '**/*'
